---
- name: Check disk space available
  hosts: "all"

  tasks:
    - name: Check disk space available
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          df -Ph /
        executable: /bin/bash
      changed_when: false
      check_mode: false
      register: disk_usage

    - name: Show disk usage
      ansible.builtin.debug:
        msg: "Disk usage is: {{ disk_usage.stdout }}"