---

- hosts: all
  #become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      ansible.builtin.apt:
      #apt:
        upgrade: dist
