---

- hosts: all
  tasks:
    - name: Set /etc/update-manager/release-upgrades to "lts"
      ansible.builtin.lineinfile:
        path: /etc/update-manager/release-upgrades
        regexp: '^Prompt='
        line: "Prompt=lts"

# The next two tasks do take some time
# They are neeeded to chain both 20.04 and 22.04 upgrades together
    - name: Run dpkg configure
      command: dpkg --configure -a

    - name: Perform a dist-upgrade
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      register: dist_upgrade

#seems to need a reboot after dist-upgrade
    - name: Reboot with a long timeout
      ansible.builtin.reboot:
        reboot_timeout: 3600
      when: dist_upgrade.changed

# This usually takes 6 minutes or so
# If you are bored, you can check the logs on the host at /var/log/dist-upgrade/main.log
    - name: Upgrade Ubuntu with the do-release-upgrade tool
      ansible.builtin.shell: |
        do-release-upgrade -f DistUpgradeViewNonInteractive
      #async: 3600
      poll: 0

    - name: Check if the server is running Ubuntu 24.04
      ansible.builtin.command: lsb_release -r
      register: os_version
      until: os_version.stdout.find('24.04') != -1
      retries: 1
      delay: 5
      become: false # This is needed as sometimes become failes before gathering new facts
      ignore_errors: true

    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory

    - name: Reset ssh connection
      ansible.builtin.meta: reset_connection

    - name: Clear known Facts
      ansible.builtin.meta: clear_facts

    - name: Reboot with a long timeout
      ansible.builtin.reboot:
        reboot_timeout: 3600

    - name: get name gather ansible_facts
      ansible.builtin.setup:
